local SETTINGS_CONFIG = {
	--[[
    PhysicsRenderSettings = {
        viewDistance = 100000,
        renderEffectWorld = true,
        renderDetail = true,
        renderStatic = true,
        renderRagdoll = true,
        renderWater = true,
    },
    MeshStreamingSettings = {
        highestPriorityEnable = true,
    },
    EnlightenRuntimeSettings = {
        localLightCullingEnable = false,
        lightProbeForceUpdate = true,
        albedoForceUpdateEnable = true,
        emissiveEnable = true,
        lightProbeEnable = true,
    },
    EmitterSystemSettings = {
        meshDrawCountLimit = 100000,
      --  minScreenArea = 1,
        meshCullingDistance = 100000,
        zBufferCullEnable = false,
        enableFixedDelta = true,
        quadPointLightsEnable = true,
        quadSpotLightsEnable = true,
        meshShadowEnable = true,
    },
    EffectManagerSettings = {
        effectQuality = 1,
    },
    DebrisSystemSettings = {
        meshDrawCountLimit  = 100000,
        meshCullingDistance  = 100000,
        meshShadowEnable  = true,
        meshViewCullingEnable  = false,
    },]]

	WorldRenderSettings = {
		shadowmapViewDistance = 1000,
		shadowmapResolution = 9000,
		dxShadowmap16BitEnable = true,
		spotLightShadowmapResolution = 2048,
		shadowmapSliceCount = 3,
		shadowmapQuality = 1,
		transparencyShadowmapsEnable = false,
		skyEnvmapResolution = 4096,
		shadowmapPoissonFilterScale = 0,
		shadowMinScreenArea = 0.025,
		shadowmapMinScreenArea = 0.025,
		shadowViewportScale = 1,
		--  shadowmapExtrusionLength = 4000,
		-- shadowmapViewDistanceScaleEnable = true,
		shadowmapMinFov = -1,
		dynamicEnvmapFilterMode = 3,
		-- maxSpotLightShadowCount = 8,
		shadowmapCullVolumeEnable = false,
		--maxSpotLightCount = 1024,
		lightOverdrawMaxLayerCount = 256,
	},
	TextureSettings = {
		-- skipMipmapCount = 0
	},
	TextureStreamingSettings = {
		poolSize = 3500000,
		poolHeadroomSize = 350000,
		-- forceMipmap = 10,
		-- mipmapsEnable = true,
		-- fadeMipmapsEnable = false,
		-- minMipmapCount = 10,
		-- maxMipmapCount = 10,
		minTextureSize = 500000,
		-- fadeMipmapTime = 0.01,
		maxTextureSizeKb = 500000,
	},
	ShaderSystemSettings = {
		maxAnisotropy = 16,
		-- mipmapBias = -2
	},
	MeshSettings = {
		shadowDistanceScale = 3500,
	},
	VisualTerrainSettings = {
		dxDisplacementMappingEnable = true,
		dxTessellatedTriWidth = 8,
		lodScale = 1,
		dxTessellationPatchFacesPerSide = 8,
		meshScatteringBuildChannelCount = 8,
		meshScatteringBuildChannelsLaunchedPerFrameCountMax = 4,
		meshScatteringInstancesPerCellMax = 8192,
		textureAtlasSampleCountXFactor = 2,
		textureAtlasSampleCountYFactor = 2,
		textureRenderJobCount = 6,
		textureRenderJobsLaunchedPerFrameCountMax = 6,
		textureCompressionQuality = -1,
		castShadowsEnable = true,
		meshScatteringInstanceCullJobCount = 6, --chack later
		meshScatteringDensityScaleFactor = 5.0,
		zPassDistance = 500,
		textureDetailFalloffFactor = 0.01,
		textureDetailFalloffDistance = 10000,
		textureDetailFalloffCurve = 10000,
		textureOccludedDetailReductionFactor = 10000,
		meshScatteringDistanceScaleFactor = 2500,
		meshScatteringDensityMarginFactor = 100,
		-- textureGenerationMipBias = 0,
		dynamicMaskDecalWidthScale = 1000,
		meshScatteringCellPoolCapacity = 4096,
		decalZPassDrawDistance = 2500,
		decal3dFarDrawDistanceScaleFactor = 1000,
		occludedMinDistance = 10000,
		forceDecalReducedQuality = false,
		dynamicMaskEnable = false,
		occluderEnable = false,

		detailOverlayEnable = true,
		cullSpuJobEnable = false,
		regenerateTexturesEnable = false,
		textureBlockOnStreamingEnable = false,
		patchLodTransitionsEnable = false,
		patchMaterialSortingEnable = false,
		textureLayerCullingEnable = false,
		--textureDrawTerrainLayersEnable = false

		drawQuadtreeZoomIndex = 1,
		drawQuadtreesEnable = true,
		drawQuadtreeStatsEnable = true,
		drawQuadtreeAtlasTexturesEnable = true,
		drawMeshScatteringQuadtreeEnable = true,
	},
	TerrainStreamingSettings = {
		heightfieldAtlasSampleCountXFactor = 1,
		heightfieldAtlasSampleCountYFactor = 2,
		maskAtlasSampleCountXFactor = 1,
		maskAtlasSampleCountYFactor = 2,
		colorAtlasSampleCountXFactor = 1,
		colorAtlasSampleCountYFactor = 2,
		loadOccluderDataEnable = false,
		keepPoolFullEnable = false,
		maskAdditionalBlurriness = 0,
		additionalBlurriness = 0,
		occludedDetailReductionFactor = 0,
		activeFreeStreamingDataLoadJobCount = 10,
	},
	VegetationSystemSettings = {
		useShadowLodOffset = false,
		maxPreSimsPerJob = 8,
		simulationMemKbClient = 4096,
		maxActiveDistance = 2500,
		forceShadowLod = 6,
		shadowMeshEnable = true,
		dissolveEnable = false,
		subDestructionEnabled = true,
	},
	GameRenderSettings = {
		edgeModelViewDistance = 1500,
		staticModelCullJobCount = 100000,
		viewDistance = 100000,
		edgeModelForceLod = -1,
		edgeModelMaxVisibleInstanceCount = 100000,
		edgeModelCullEnable = false,
		staticModelPartCullEnable = false,
		staticModelPartShadowCullEnable = false,
		staticModelCullSpuJobEnable = false,
	},
}

g_Prints = true

return SETTINGS_CONFIG
